accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('sign-up', views.SignUpView.as_view(), name='signup'),
    path('log-in', views.LoginView.as_view(), name='custom_login'), #url 'login' is used by django.auth and I dont know how to get rid of it, so I am using 'log-in' instead
    path('groups', views.GroupListView.as_view(), name='groups'),
    path('invites', views.invites, name='invites'),
    path('cancel-invite/<int:invite_id>', views.cancel_invite, name='cancel_invite'),
    path('invite/<int:group_id>', views.invite, name='invite'),
    path('send-invite', views.send_invite, name='send_invite'),
    path('leave-group/<int:group_id>', views.leave_group, name='leave_group'),
    path('accept-invite/<int:invite_id>', views.accept_invite, name='accept_invite'),
    path('decline-invite/<int:invite_id>', views.decline_invite, name='decline_invite'),
    path('create-group-form', views.get_group_form, name='get_group_form'),
    path('create-group', views.create_group, name='create_group'),
]

diary/urls.py
from django.urls import path, include

from . import views

#to differentiate between template names across apps, namescape them:
#app_name = 'diary' #and then in the template: {% url 'diary:urlname' %}
urlpatterns = [
    path('', views.get_diaries, name='diaries'),
    path('new-diary-form', views.new_diary_form, name='diary_form'),
    path('create-diary', views.create_diary, name='create_diary'),
    path('diary/<int:diary_id>/', include([
        path('', views.get_diary, name='diary'),
        path('chapter/<int:day>/<int:month>/<int:year>/', include([
            path('', views.get_diary, name='diary_with_chapter'),
            path('json', views.get_chapter, name='chapter'),
            path('tab/<str:tab>', views.get_diary, name='diary_with_chapter_tab'),
            path('new-story-form', views.new_story_form, name='story_form'),
            path('create-story', views.create_story, name='create_story'),
            path('new-note-form', views.new_note_form, name='note_form'),
            path('create-note', views.create_note, name='create_note'),
            path('new-tasklist-form', views.new_tasklist_form, name='tasklist_form'),
            path('create-tasklist', views.create_tasklist, name='create_tasklist'),
        ]))
    ])),
    path('update-note/<int:note_id>', views.update_note, name='update_note'),
    path('delete-note/<int:note_id>', views.delete_note, name='delete_note'),
    path('update-task-list/<int:tasklist_id>', views.update_tasklist, name='update_tasklist'),

]

djangoWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')), #for registration etc., it is useful to have it divided once there are more apps in the project than just one
    path('account/', include('django.contrib.auth.urls')),
    path('diaries/', include('diary.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index') #possibly make a dedicated "pages" app, once there are more apps than just the diary
]

diary/models.py
from django.db import models
from accounts.models import Group, User


# Create your models here.




class Diary(models.Model):
    """Zero or more diaries per group"""
    group = models.ForeignKey(Group, on_delete=models.CASCADE) #each User might have a group, which only he belongs to (this way there is no need for some inheritance, where the would be smth like "Owner", from which would User and Group inherit.
    name = models.CharField(max_length=100)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Chapter(models.Model):
    """Zero or one chapter in a diary per day"""
    diary = models.ForeignKey(Diary, on_delete=models.CASCADE)
    date = models.DateField('date that the chapter belongs to')
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} ({})".format(self.diary.name, self.date)

class Story(models.Model):
    """Zero or more stories per chapter"""
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100)
    text = models.TextField()
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return "{} ({}): {}".format(self.chapter.diary.name, self.chapter.date, self.title)

# class Note(models.Model):
#     """One note per chapter (can be used as a task list for that day)"""
#     chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return "{} ({}): {}".format(self.chapter.diary.name, self.chapter.date, self.title)

class Note(models.Model):
    """Zero or more notes per Chapter"""
    #note = models.ForeignKey(Note, on_delete=models.CASCADE)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    text = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return "{} ({})".format(self.chapter.diary.name, self.chapter.date)

class TaskList(models.Model):
    """Zero or more task lists per Chapter"""
    #note = models.ForeignKey(Note, on_delete=models.CASCADE)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return "{} ({}): {}".format(self.chapter.diary.name, self.chapter.date, self.name)

class Task(models.Model):
    """Zero or more tasks per TaskList"""
    task_list = models.ForeignKey(TaskList, on_delete=models.CASCADE)
    is_finished = models.BooleanField(default=False)
    text = models.CharField(max_length=500)
    last_modified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return "{} ({}): {}".format(self.task_list.chapter.diary.name, self.task_list.chapter.date, self.task_list.name)

diary/forms.py
from django import forms

from accounts.models import Group
from djangoWebApp.forms import  StyledModelForm

from diary.models import Diary, Story, Note, TaskList


class DiaryForm(StyledModelForm):
    # fields can be changed like this, so forms.ModelForm can still be used instead of forms.Form
    group = forms.ModelChoiceField(required=False, queryset=Group.objects.none(), help_text='Leave it empty to automatically create a new group with you in it.')

    class Meta:
        model = Diary
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['group'].queryset = user.group_set.all() #if using permissions, then use Membership.objects

class StoryForm(StyledModelForm):

    class Meta:
        model = Story
        fields = ('title', 'text')

class NoteForm(StyledModelForm):

    class Meta:
        model = Note
        fields = ('text',)

class TaskListForm(StyledModelForm):
    class Meta:
        model = TaskList
        fields = ('name',)

diary/views.py
import datetime
import json

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string

from accounts.models import Group
from djangoWebApp.utils import chunks
from .forms import DiaryForm, StoryForm, NoteForm, TaskListForm
from .models import Diary, Chapter, Story, Note, TaskList, Task


# Create your views here.

@login_required
def get_diaries(request):
    # select diaries which belong to one of the groups that the user is in
    groups = request.user.group_set.all()
    diaries = Diary.objects.filter(group__in=groups)  # group__id__in=groups.values_list('id')
    # divide the list into groups of 4
    chunked_diaries = chunks(diaries, 4)
    return render(request, 'diary/diaries.html', {'chunked_diaries': chunked_diaries})


@login_required
def new_diary_form(request):
    diary_form = DiaryForm(user=request.user)

    return render(request, 'diary/diary_form.html', {'diary_form': diary_form})


@login_required
def create_diary(request):
    if request.method == 'POST':
        diary_form = DiaryForm(request.POST, user=request.user)
        if diary_form.is_valid():  # it also validates that the group is one of the groups that user is in
            name = diary_form.cleaned_data['name']
            group = diary_form.cleaned_data['group']
            # create a new group if none was selected
            if group is None:
                group_name = '{}: {}'.format(request.user.username, name)
                group = Group(name=group_name)
                group.save()
                group.users.add(request.user)
            diary = Diary(name=name, group=group)
            diary.save()

    return redirect('diaries')


@login_required
def get_diary(request, diary_id, day=None, month=None, year=None, tab="stories"):
    diary = get_object_or_404(Diary, pk=diary_id)
    if not diary.group.users.filter(id=request.user.id).exists():
        return HttpResponse(status=403)

    return render(request, 'diary/diary.html', {'diary': diary, 'day': day,
                                                'month': month, 'year': year,
                                                'tab': tab})


def get_chapter_or_404(diary_id, day, month, year):
    date = datetime.date(year, month, day)
    chapter = get_object_or_404(Chapter, diary__id=diary_id, date=date)
    return chapter


@login_required
def get_chapter(request, diary_id, day, month, year):
    diary = Diary.objects.get(pk=diary_id)
    if not diary.group.users.filter(id=request.user.id).exists():
        return HttpResponse(status=403)

    date = datetime.date(year, month, day)
    try:
        chapter = Chapter.objects.get(diary__id=diary_id, date=date)
    except Chapter.DoesNotExist:
        chapter = Chapter(diary=diary, date=date)
        chapter.save()


    # there might be a better solution to this
    parent_url = {'diary_id': diary_id, 'day': day, 'month': month, 'year': year}

    stories_html = render_to_string('diary/stories.html', {'stories': chapter.story_set.all(),
                                                           'url': parent_url, 'user': request.user}, request)
    notes_html = render_to_string('diary/notes.html', {'notes': chapter.note_set.all(),
                                                       'url': parent_url, 'user': request.user}, request)
    tasklists_html = render_to_string('diary/tasklists.html', {'tasklists': chapter.tasklist_set.all(),
                                                               'url': parent_url, 'user': request.user}, request)
    return JsonResponse({'stories': stories_html, 'notes': notes_html, 'tasklists': tasklists_html})


@login_required
def new_story_form(request, diary_id, day, month, year):
    chapter = get_chapter_or_404(diary_id, day, month, year)
    if not chapter.diary.group.users.filter(id=request.user.id).exists():
        return HttpResponse(status=403)

    parent_url = {'diary_id': diary_id, 'day': day, 'month': month, 'year': year}
    story_form = StoryForm()
    return render(request, 'diary/story_form.html', {'story_form': story_form, 'url': parent_url})


@login_required
def create_story(request, diary_id, day, month, year):
    chapter = get_chapter_or_404(diary_id, day, month, year)
    if not chapter.diary.group.users.filter(id=request.user.id).exists():
        return HttpResponse(status=403)

    if request.method == 'POST':
        story_form = StoryForm(request.POST)
        if story_form.is_valid():
            title = story_form.cleaned_data['title']
            text = story_form.cleaned_data['text']
            story = Story(chapter=chapter, title=title, text=text, author=request.user)
            story.save()

    return redirect('diary_with_chapter_tab', diary_id=diary_id,
                    day=day, month=month, year=year, tab="stories")



@login_required
def new_note_form(request, diary_id, day, month, year):
    chapter = get_chapter_or_404(diary_id, day, month, year)
    if not chapter.diary.group.users.filter(id=request.user.id).exists():
        return HttpResponse(status=403)

    parent_url = {'diary_id': diary_id, 'day': day, 'month': month, 'year': year}
    note_form = NoteForm()
    return render(request, 'diary/note_form.html', {'note_form': note_form, 'url': parent_url})


@login_required
def create_note(request, diary_id, day, month, year):
    chapter = get_chapter_or_404(diary_id, day, month, year)
    if not chapter.diary.group.users.filter(id=request.user.id).exists():
        return HttpResponse(status=403)

    if request.method == 'POST':
        note_form = NoteForm(request.POST)
        if note_form.is_valid():
            text = note_form.cleaned_data['text']
            note = Note(chapter=chapter, text=text, author=request.user)
            note.save()

    return redirect('diary_with_chapter_tab', diary_id=diary_id,
                    day=day, month=month, year=year, tab="notes")


@login_required
def update_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    # if not note.chapter.diary.group.users.filter(id=request.user.id).exists():
    if note.author is not None and note.author != request.user:
        return HttpResponse(status=403)

    if request.method == 'POST':
        # is there any disadvantage compared to defining an UpdateForm in this case?
        # I dont't think so (the is_valid() wouldn't really do anything)
        text = request.POST.get('text', '')
        note.text = text
        note.save()

    date = note.chapter.date
    return redirect('diary_with_chapter_tab', diary_id=note.chapter.diary.id,
                    day=date.day, month=date.month, year=date.year, tab="notes")


@login_required
def delete_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    # if not note.chapter.diary.group.users.filter(id=request.user.id).exists():
    if note.author is not None and note.author != request.user:
        return HttpResponse(status=403)

    if request.method == 'POST':
        note.delete()

    date = note.chapter.date
    return redirect('diary_with_chapter_tab', diary_id=note.chapter.diary.id,
                    day=date.day, month=date.month, year=date.year, tab="notes")


@login_required
def new_tasklist_form(request, diary_id, day, month, year):
    chapter = get_chapter_or_404(diary_id, day, month, year)
    if not chapter.diary.group.users.filter(id=request.user.id).exists():
        return HttpResponse(status=403)

    parent_url = {'diary_id': diary_id, 'day': day, 'month': month, 'year': year}
    tasklist_form = TaskListForm()
    return render(request, 'diary/tasklist_form.html', {'tasklist_form': tasklist_form, 'url': parent_url})


@login_required
def create_tasklist(request, diary_id, day, month, year):
    chapter = get_chapter_or_404(diary_id, day, month, year)
    if not chapter.diary.group.users.filter(id=request.user.id).exists():
        return HttpResponse(status=403)

    if request.method == 'POST':
        tasklist_form = TaskListForm(request.POST)
        if tasklist_form.is_valid():
            name = tasklist_form.cleaned_data['name']
            tasklist = TaskList(chapter=chapter, name=name, author=request.user)
            tasklist.save()

    return redirect('diary_with_chapter_tab', diary_id=diary_id,
                    day=day, month=month, year=year, tab="tasklists")



@login_required
@transaction.atomic
def update_tasklist(request, tasklist_id):
    tasklist = get_object_or_404(TaskList, pk=tasklist_id)
    # if tasklist.author is not None and tasklist.author != request.user:
    if not tasklist.chapter.diary.group.users.filter(id=request.user.id).exists():
        return HttpResponse(status=403)

    if request.method == 'POST':
        tasks_data = json.loads(request.body)
        # replace all tasks with the sent list
        tasklist.task_set.all().delete()
        for task in tasks_data:
            task = Task(text=task['text'], is_finished=task['is_finished'],
                              task_list=tasklist, author=request.user)
            task.save()

        return HttpResponse(status=200)
    else:
        return HttpResponse(status=405)

templates/diary/diaries.html
{% extends 'base.html' %}
{% block title %}Diaries{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'diary_form' %}" class="btn btn-primary btn-md">
         <i class="fas fa-plus"></i> New diary
        </a>
    </div>

    <div>
        {% for diary_list in chunked_diaries %}
            <div class="row mt-4">
                {% for diary in diary_list %}
                 <!-- there needs to be a wrapper with padding instead of just one div with margin
                  because if one col spans the whole screen (on mobile),
                  then the margin will cause it to not fit and make a horizontal scroll-->
                    <div class="col-md-2 px-3">
                        <!-- transform is used only so that the container for 'stretched-link' is determined properly -->
                        <div class="p-3 mt-4 bg-light border " style="transform: rotate(0);">
                            <a class="stretched-link" href="{% url 'diary' diary.id %}">
                                {{ diary.name }} <small>({{diary.group.name}})</small>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>

        {% endfor %}
    </div>
{% endblock %}

templates/diary/diary.html
{% extends 'base.html' %}
{% load static %} <!-- has to be loaded explicitly in each file -->
{% block title %}Diary{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'calendar/calendar.css' %}"/>
    <link rel="stylesheet" href="{% static 'diary/tasklists.css' %}"/>
{% endblock %}

{% block content %}
    <h2>{{diary.name}}</h2>


<div class="row pt-4">
    <div class="col-md-6" id="chapter"
         {% if day is not None %}
            data-date="{{day}}" data-month="{{month}}" data-year="{{year}}"
         {% endif %}
    >
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link {% if tab == 'stories' %}active{% endif %}" id="stories-tab" data-bs-toggle="tab" data-bs-target="#stories" type="button"
                        role="tab" aria-controls="stories" aria-selected="true">Stories
                </button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link {% if tab == 'notes' %}active{% endif %}" id="notes-tab" data-bs-toggle="tab" data-bs-target="#notes" type="button"
                        role="tab" aria-controls="notes" aria-selected="false">Notes
                </button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link {% if tab == 'tasklists' %}active{% endif %}" id="tasklists-tab" data-bs-toggle="tab" data-bs-target="#tasklists" type="button"
                        role="tab" aria-controls="tasklists" aria-selected="false">Task lists
                </button>
            </li>
        </ul>
        <div class="tab-content mt-4" id="chapter-tab-content">
            <div class="tab-pane fade {% if tab == 'stories' %} show active {% endif %}" id="stories" role="tabpanel" aria-labelledby="stories-tab"></div>
            <div class="tab-pane fade {% if tab == 'notes' %} show active {% endif %}" id="notes" role="tabpanel" aria-labelledby="notes-tab"></div>
            <div class="tab-pane fade {% if tab == 'tasklists' %} show active {% endif %}" id="tasklists" role="tabpanel" aria-labelledby="tasklists-tab"></div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="sticky-top">
            <h3 id="monthAndYear"></h3>
            <div class="button-container-calendar">
                <button class="btn btn-secondary btn-md" id="previous" onclick="previous()">&#8249;</button>
                <button class="btn btn-secondary btn-md" id="next" onclick="next()">&#8250;</button>
            </div>

            <table class="table-calendar" id="calendar" data-lang="en">
                <thead id="thead-month"></thead>
                <tbody id="calendar-body"></tbody>
            </table>

            <div class="d-flex flex-row my-3 align-items-center">
                <div>
                    <label for="month">Jump to:</label>
                </div>
                <div class="px-1">
                    <select id="month" onchange="jump()" class="form-control">
                        <option value=0>Jan</option>
                        <option value=1>Feb</option>
                        <option value=2>Mar</option>
                        <option value=3>Apr</option>
                        <option value=4>May</option>
                        <option value=5>Jun</option>
                        <option value=6>Jul</option>
                        <option value=7>Aug</option>
                        <option value=8>Sep</option>
                        <option value=9>Oct</option>
                        <option value=10>Nov</option>
                        <option value=11>Dec</option>
                    </select>
                </div>
                <div class="pe-4">
                    <select id="year" onchange="jump()" class="form-control"></select>
                </div>
                <div class="ps-2">
                    <button class="btn btn-secondary" onclick="jumpToToday()">Today</button>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'calendar/calendar.js' %}" type="text/javascript"></script>

<script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
<script src="{% static 'diary/tasklists.js' %}" type="text/javascript"></script>
{% endblock %}

templates/diary/diary_form.html
{% extends 'base.html' %}
{% block title %}Group form{% endblock %}

{% block content %}
    <form class="w-50" method="POST" action="{% url 'create_diary' %}">
        {% csrf_token %}
        <div class="form-group">
        {{ diary_form.as_p }}
        </div>
        <input class="btn btn-secondary btn-md" type="submit" value="Create diary"/>
    </form>
{% endblock %}

templates/diary/note_form.html
{% extends 'base.html' %}
{% block title %}Note form{% endblock %}

{% block content %}
    <form class="w-50" method="POST" action="{% url 'create_note' url.diary_id url.day url.month url.year%}">
        {% csrf_token %}
        <div class="form-group">
        {{ note_form.as_p }}
        </div>
        <input class="btn btn-secondary btn-md" type="submit" value="Create note"/>
    </form>
{% endblock %}

templates/diary/notes.html
<div>
    <a href="{% url 'note_form' url.diary_id url.day url.month url.year %}" class="btn btn-primary btn-md">
         <i class="fas fa-plus"></i> New note
    </a>
</div>

<div class="mt-4">
    {% for note in notes %}
        <div class="d-flex flex-row gap-4 mb-2">
            <div>
                <em>{{note.creation_date|date:"G:i"}}, Last modified: </em>
                <em id="last-modified">{{note.last_modified|date:"G:i"}}</em>
                <em>
                    {% if note.author %}
                    ({{note.author.username}})
                    {% endif %}
                </em>
            </div>
            <div>
                {% if note.author is None or note.author == user %}
                <button class="btn btn-secondary btn-sm mb-2 ms-1" onclick="modifyNote({{note.id}})">
                    Modify
                </button>
                 <button class="btn btn-secondary btn-sm mb-2 ms-1" onclick="deleteNote({{note.id}})">
                    Delete
                </button>
                <form id="deleteNoteForm-{{note.id}}" style="display: none;  " method="POST" action="{% url 'delete_note' note.id %}">
                    {% csrf_token %}
                    <!-- <input name="note_id" type="number" value="{{note.id}}"/> -->
                </form>
                {% endif %}
            </div>
        </div>
        <div id="note-text-{{note.id}}">{{note.text|linebreaks}}</div>
        {% if note.author is None or note.author == user %}
        <form id="note-form-{{note.id}}" style="display: none;  " method="POST" action="{% url 'update_note' note.id %}">
            {% csrf_token %}
            <p>
                <textarea name="text" id="note-textarea-{{note.id}}" class="form-control"></textarea>
            </p>
            <div class="d-flex flex-row-reverse gap-2">
                <input type="submit" class="btn btn-primary" value="Confirm"/>
                <input type="button" class="btn btn-secondary" value="Cancel" onclick="cancelNoteModification({{note.id}})"/>
            </div>
        </form>
        {% endif %}
        <hr/>
    {% endfor %}
</div>

templates/diary/stories.html
<div>
    <!-- maybe there is a better way to do this without hardcoding it
    (this hardcoded version works: {request.path}}story-form
    (but the url would have to be updated when sending the AJAX))
    (in a way it is less hardcoded than the current version...)-->
    <a href="{% url 'story_form' url.diary_id url.day url.month url.year %}" class="btn btn-primary btn-md">
         <i class="fas fa-plus"></i> New story
    </a>
</div>

<div class="mt-4">
    {% for story in stories %}
        <h3>{{story.title}}
            <small class="text-muted">
                ({{story.creation_date|date:"G:i"}}{% if story.author %}, {{story.author}}{% endif %})
            </small>
        </h3>
        <div>{{story.text|linebreaks}}</div>
    {% endfor %}
</div>

templates/diary/story_form.html
{% extends 'base.html' %}
{% block title %}Story form{% endblock %}

{% block content %}
    <form class="w-50" method="POST" action="{% url 'create_story' url.diary_id url.day url.month url.year%}">
        {% csrf_token %}
        <div class="form-group">
        {{ story_form.as_p }}
        </div>
        <input class="btn btn-secondary btn-md" type="submit" value="Create story"/>
    </form>
{% endblock %}

templates/diary/tasklist_form.html
{% extends 'base.html' %}
{% block title %}Task list form{% endblock %}

{% block content %}
    <form class="w-50" method="POST" action="{% url 'create_tasklist' url.diary_id url.day url.month url.year%}">
        {% csrf_token %}
        <div class="form-group">
        {{ tasklist_form.as_p }}
        </div>
        <input class="btn btn-secondary btn-md" type="submit" value="Create task list"/>
    </form>
{% endblock %}

templates/diary/tasklists.html
<div>
    <a href="{% url 'tasklist_form' url.diary_id url.day url.month url.year %}" class="btn btn-primary btn-md">
         <i class="fas fa-plus"></i> New task list
    </a>
</div>

<div class="mt-4">
    {% for tasklist in tasklists %}
        <h3>{{tasklist.name}}</h3>
        <div class="list-group" id="tasklist-{{tasklist.id}}">
            {% for task in tasklist.task_set.all %}
            <button class="list-group-item list-group-item-action d-flex justify-content-between
            {% if task.is_finished %} finished {% endif %}"
            id="task-{{task.id}}"
            data-text="{{task.text}}"
            onclick="taskClicked(this)">
                <div class="d-flex align-items-center gap-2">
                    <i class="fas fa-check {% if not task.is_finished %}hidden{% endif %}"></i>
                    <div class="task-text">{{task.text}} <em>{% if task.author %}({{task.author}}){% endif %}</em></div>
                </div>
                <div onclick="deleteTask('task-{{task.id}}')">
                    <i class="fas fa-times"></i>
                </div>
            </button>
            {% endfor %}
        </div>
        <textarea class="form-control mt-3 mb-2" rows="2" id="taskTA-{{tasklist.id}}"></textarea>
        <div class="d-flex flex-row-reverse gap-2 mb-2">
            <button class="btn btn-secondary btn-md" onclick="updateTaskList({{tasklist.id}})">Save</button>
            <button class="btn btn-secondary btn-md" onclick="addTask({{tasklist.id}})">Add task</button>
        </div>
            <!--
        <form style="display: none;">
        </form> -->
    {% endfor %}
</div>